#!/usr/bin/env php
<?php
/**
 * Yii 控制台引导文件
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

// fcgi 默认没有定义 STDIN 和 STDOUT
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/Yii.php');

$application = new yii\console\Application([
    'id' => 'yii-console',
    'basePath' => __DIR__ . '/console',
]);
$exitCode = $application->run();
exit($exitCode);
